implement ui and interfaces
android-on-MarsLviv/PictureN pull request #1
Opened 2021-05-07 16:56 UTC by MarsLviv

2021-05-11 08:18 UTC, gutachkee requested changes
There are no required changes.
The task was:
1. Create UI. Layout is defined, but no Java code is present. Button click handling? EditText value read? I expect this PR to contain all code related to the UI.
2. Define JNI interface. Interface which will be used for capturing the frame. But there is no way how to receive frame from the native. No implementation is required, just the interface.

Few things to learn:
1. Always do self review before pushing the change. This PR contain only few small  files created by yourself and they contain fomatting issues, deps duplicates..
2. If the task is not clear, **you should always ask for clarification.**

2021-05-11 08:18 UTC, gutachkee commented on .gitignore
> +/.idea/assetWizardSettings.xml
I would rather ignore all Idea files. It likes to do a lot of changes there periodically. No need to store them in VCS  
```suggestion
.idea
```

2021-05-11 08:18 UTC, gutachkee commented on app/build.gradle
> +
```suggestion
```

2021-05-11 08:18 UTC, gutachkee commented on app/src/main/jni/def.h
> +#ifdef __ANDROID__
if you're using checks for \_\_ANDROID\_\_, then I believe you should put `#include <android/log.h>` line inside ifdef.

From the other hand, we do not expect this code to be built without NDK, so there is no need to have it(ifdef) at all. 
(But we would need to have it is case when we want the code to be compiled without NDK, i.e. for some other platforms)

2021-05-11 08:18 UTC, gutachkee commented on app/src/test/java/com/example/picturen/ExampleUnitTest.java
> +}
We will modify it for our needs in future. But lets keep it as is for now.

2021-05-11 08:18 UTC, gutachkee commented on app/src/main/jni/CMakeLists.txt
> +            capture.cpp )
formatting
```suggestion
add_library(capture
            SHARED
            capture.cpp
)
```

2021-05-11 08:18 UTC, gutachkee commented on app/src/main/jni/CMakeLists.txt
> +                        log )
again: formatting.
findLibrary with log log?
```suggestion
find_library(
        log
)

target_link_libraries(
        capture
        log
)
```
ALWAYS DO SELF REVIEW BEFORE PUSHING THE CHANGE

2021-05-11 08:18 UTC, gutachkee commented on app/src/main/jni/def.h
> +
Let's have this file as log_utils.h.

What 'def.h' means?

2021-05-11 08:18 UTC, gutachkee commented on app/src/main/java/com/example/picturen/SavePicture.java
> +public interface SavePicture {
Remove entire file.

2021-05-11 13:24 UTC, MarsLviv commented on app/src/main/java/com/example/picturen/SavePicture.java
> +public interface SavePicture {
In order to pursue Dependency inversion principle I created this interface.
Implementation classes will save picture on Disk, on Cloud starage, on  social services, etc

2021-05-11 13:26 UTC, MarsLviv commented on app/src/main/jni/CMakeLists.txt
> +                        log )
find_library command require at least two parameters

2021-05-13 12:16 UTC, gutachkee commented on app/src/main/java/com/example/picturen/FrameWriterSD.java
> +        saveCallback.onSave();
```suggestion
        // todo: do the implementation
        saveCallback.onSave();
```

2021-05-13 12:16 UTC, gutachkee commented on app/src/main/java/com/example/picturen/NativeCamera.java
> +        byte[] frame = (byte[]) capture();
```suggestion
        byte[] frame = capture();
```

2021-05-13 12:17 UTC, gutachkee approved these changes
Resolve few additional comments and feel free to merge.

2021-05-13 12:20 UTC, MarsLviv commented on app/src/main/java/com/example/picturen/FrameWriterSD.java
> +        saveCallback.onSave();
done

2021-05-13 12:20 UTC, MarsLviv commented on app/src/main/java/com/example/picturen/NativeCamera.java
> +        byte[] frame = (byte[]) capture();
done

2021-05-14 05:44 UTC, merged